language: c

install:
  - echo "deb http://debian.meebey.net/experimental/mono /" > pgdg.list
  - sudo mv pgdg.list /etc/apt/sources.list.d/
  - sudo apt-get update
  - sudo apt-get -y --force-yes install mono-devel
  - mozroots --import --sync
  - export EnableNuGetPackageRestore=true

script:
  - xbuild build/DatingsWithNancy.proj
